version: ">= 0.14.0"

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-tenant-span-source-group/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-tenant-span-source-group/actions/workflows/test.yml)

  *This module is no longer maintained as it has been integrated into the [nac-aci](https://github.com/netascode/terraform-aci-nac-aci) module.*

  # Terraform ACI Tenant SPAN Source Group Module

  Manages ACI Tenant SPAN Source Group

  Location in GUI:
  `Tenants` » `Policies` » `Troubleshooting` » `SPAN` » `SPAN Source Groups`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
